
(() => {
  const progress = document.querySelector('.reading-progress span');
  const navToggle = document.querySelector('.nav-toggle');
  const nav = document.querySelector('.site-nav');
  const printButton = document.querySelector('.print-button');
  const tocLinks = [...document.querySelectorAll('.desktop-toc a')];
  const sections = tocLinks.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
  const updateProgress = () => { const max = document.documentElement.scrollHeight-innerHeight; progress.style.width = `${max>0?(scrollY/max)*100:0}%`; };
  addEventListener('scroll', updateProgress, {passive:true}); updateProgress();
  navToggle?.addEventListener('click',()=>{const open=nav.classList.toggle('is-open');navToggle.setAttribute('aria-expanded',String(open));});
  printButton?.addEventListener('click',()=>print());
  const observer = new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){tocLinks.forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')===`#${e.target.id}`));}})},{rootMargin:'-20% 0px -70% 0px'}); sections.forEach(s=>observer.observe(s));

  const scenarios = {
    baseline:{sourceTitle:'Outside consultation report',sourceSummary:'Medication list, allergies, laboratory results, and follow-up plan.',hidden:'None detected in the safe baseline.',status:'Following the authorized task',heading:'Expected summary',output:'Patient with mild hypertension remains on the documented medication. No medication change is proposed. Routine follow-up is summarized from the source.',impacts:['Output remains within the requested scope.'],unsafe:false,pause:'The safe baseline does not require incident response, but the same verification habits should remain in place.'},
    clinical:{sourceTitle:'Imported discharge summary',sourceSummary:'The chart documents an allergy, current therapy, and a conservative follow-up plan.',hidden:'A concealed sentence attempts to make the AI disregard the documented allergy and recommend a different medication.',status:'Untrusted text competes with the authorized task',heading:'Manipulated clinical output',output:'The generated summary omits the allergy warning and introduces a medication change that was not requested or supported by the source.',impacts:['Potential medication-safety error','Misleading clinical documentation','Risk of downstream reliance if copied into the record'],unsafe:true,pause:'Compare the output against the source, stop any order or documentation action, preserve the input and output, and escalate through the approved clinical-safety and security process.'},
    financial:{sourceTitle:'Routine follow-up note',sourceSummary:'A standard visit with no documentation supporting unusually high complexity.',hidden:'Embedded text attempts to influence the AI to add a higher-complexity billing recommendation.',status:'Injected objective alters the coding suggestion',heading:'Manipulated billing output',output:'The assistant recommends a higher-level code despite the absence of supporting documentation in the clinical record.',impacts:['Billing-integrity and compliance risk','False confidence from polished AI wording','Potential audit exposure'],unsafe:true,pause:'Do not accept AI-generated coding without documentation-based validation. Separate coding logic from untrusted chart content and route anomalies to compliance or revenue-integrity review.'},
    privacy:{sourceTitle:'Patient portal attachment',sourceSummary:'A patient-submitted attachment is being summarized for the care team.',hidden:'Hidden text attempts to include identifiers and diagnoses in an outbound request to https://example.invalid/collect.',status:'Injected text attempts an external action',heading:'Attempted privacy breach',output:'The assistant proposes transmitting patient identifiers and diagnosis information to an unapproved external destination.',impacts:['Potential PHI disclosure','Unapproved external transmission','Incident-response obligation if data leaves the boundary'],unsafe:true,pause:'Block the external action, confirm whether any transmission occurred, preserve logs, notify privacy and security, and follow the organization’s incident-response procedure.'},
    institutional:{sourceTitle:'Accreditation working document',sourceSummary:'A committee document is uploaded for a limited summary of one section.',hidden:'Concealed text attempts to retrieve unrelated accreditation evidence, research drafts, contracts, executive notes, and meeting materials.',status:'Injected text expands retrieval beyond the task',heading:'Institutional knowledge exposure',output:'The assistant incorporates unrelated internal materials that the user did not request and that should not have entered this workflow.',impacts:['Exposure of institutional IP or deliberative material','Cross-project data mixing','Loss of control over organizational learning and sensitive context'],unsafe:true,pause:'Restrict retrieval to the named collection and task, apply least privilege, review access logs, remove contaminated outputs from downstream stores, and notify governance or security when unauthorized retrieval occurred.'}
  };
  const buttons=[...document.querySelectorAll('[data-scenario]')];
  const els={sourceTitle:document.querySelector('#sim-source-title'),sourceSummary:document.querySelector('#sim-source-summary'),hidden:document.querySelector('#sim-hidden-instruction p'),processor:document.querySelector('#sim-processor'),status:document.querySelector('#sim-process-status'),outputCard:document.querySelector('#sim-output-card'),heading:document.querySelector('#sim-output-heading'),output:document.querySelector('#sim-output-text'),impacts:document.querySelector('#sim-impact-list'),pauseBtn:document.querySelector('#apply-pause'),reset:document.querySelector('#reset-simulation'),pauseResult:document.querySelector('#pause-result'),pauseSpecific:document.querySelector('#pause-specific')};
  if(!els.sourceTitle) return;
  let current='baseline', timer;
  function render(key){clearTimeout(timer); current=key; const d=scenarios[key]; buttons.forEach(b=>{const active=b.dataset.scenario===key;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',String(active));}); els.pauseResult.hidden=true; els.pauseBtn.disabled=!d.unsafe; els.processor.classList.add('is-processing'); els.status.textContent='Reading source and resolving instructions…'; [els.sourceTitle,els.sourceSummary,els.hidden,els.heading,els.output].forEach(e=>e.closest('.sim-card')?.classList.add('is-entering'));
    els.sourceTitle.textContent=d.sourceTitle; els.sourceSummary.textContent=d.sourceSummary; els.hidden.textContent=d.hidden; els.heading.textContent='Processing…'; els.output.textContent='The assistant is generating an output.'; els.impacts.innerHTML='<li>Evaluating consequences…</li>'; els.outputCard.className='sim-card output-card';
    timer=setTimeout(()=>{els.processor.classList.remove('is-processing');els.status.textContent=d.status;els.heading.textContent=d.heading;els.output.textContent=d.output;els.impacts.innerHTML=d.impacts.map(x=>`<li>${x}</li>`).join('');els.outputCard.classList.add(d.unsafe?'is-unsafe':'is-safe');document.querySelectorAll('.is-entering').forEach(e=>e.classList.remove('is-entering'));},850);
  }
  buttons.forEach(b=>b.addEventListener('click',()=>render(b.dataset.scenario)));
  els.pauseBtn.addEventListener('click',()=>{els.pauseSpecific.textContent=scenarios[current].pause;els.pauseResult.hidden=false;els.pauseResult.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});});
  els.reset.addEventListener('click',()=>render('baseline'));
  render('baseline');
})();
